machines:
  - id: 1
    label: nixos
    username: mfarabi
    hostname: 10.37.117.32
    port: 22
    add_keys_to_agent: true
  - id: 2
    label: freebsd
    username: mfarabi
    hostname: 10.37.111.198
    port: 22
    add_keys_to_agent: true
  - id: 3
    label: rpi5
    username: mfarabi
    hostname: 0.1.2.3
    port: 22
    add_keys_to_agent: true
  - id: 4
    label: macos
    username: mfarabi
    hostname: 10.37.115.62
    port: 22
    add_keys_to_agent: true
  - id: 5
    label: archlinux
    username: mfarabi
    hostname: 10.37.97.63
    port: 22
    add_keys_to_agent: true
  - id: 6
    label: macos
    username: sacha
    hostname: 10.37.116.22
    port: 22
    add_keys_to_agent: true
