machines:
  - id: 1
    label: nixos-1
    username: mfarabi
    hostname: 10.37.117.32
    port: 22
    add_keys_to_agent: true
  - id: 2
    label: freebsd
    username: mfarabi
    hostname: 10.37.111.198
    port: 22
    add_keys_to_agent: true
  - id: 3
    label: rpi5
    username: mfarabi
    hostname: 10.37.103.163
    port: 22
    add_keys_to_agent: true
  - id: 4
    label: macos
    username: mfarabi
    hostname: 10.37.115.62
    port: 22
    add_keys_to_agent: true
  - id: 5
    label: archlinux
    username: mfarabi
    hostname: 10.37.97.63
    port: 22
    add_keys_to_agent: true
  - id: 6
    label: nixos-2
    username: mfarabi
    hostname: 10.37.101.90
    port: 22
    add_keys_to_agent: true
