machines:
  - id: 1
    username: nixos
    hostname: 10.37.117.32
    port: 22
    user: mfarabi
  - id: 2
    username: freebsd
    hostname: 10.37.111.19
    port: 22
    user: mfarabi
  - id: 3
    username: rpi5
    hostname: 10.37.117.32
    port: 22
    user: mfarabi
  - id: 4
    username: macos
    hostname: 10.37.115.62
    port: 22
    user: mfarabi
