$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json

metadata:
  winget:
    processor:
      identifier: "dscv3"

resources:
- name: Microsoft.WinGet/Package_t5ntu4l7
  type: Microsoft.WinGet/Package
  metadata:
    description: "Configure Microsoft.PowerShell"
  properties:
    id: "Microsoft.PowerShell"
    source: "winget"

- name: Microsoft.WinGet/UserSettingsFile-0
  type: Microsoft.WinGet/UserSettingsFile
  properties:
    settings:
      $schema: "https://aka.ms/winget-settings.schema.json"

- name: Microsoft.WinGet/AdminSettings-0
  type: Microsoft.WinGet/AdminSettings
  metadata:
    winget:
      securityContext: "elevated"
  properties:
    settings:
      LocalManifestFiles: false
      ProxyCommandLineOptions: false
      BypassCertificatePinningForMicrosoftStore: false
      InstallerHashOverride: false
      LocalArchiveMalwareScanOverride: false

- name: Microsoft.DSC.Transitional/RunCommandOnSet_f14a1y0q
  type: Microsoft.DSC.Transitional/RunCommandOnSet
  metadata:
    description: "Configure Microsoft.Windows.Settings"
  dependsOn:
  - Microsoft.WinGet/Package_t5ntu4l7
  properties:
    arguments:
    - "-NoProfile"
    - "-NoLogo"
    - "-Command"
    - "if (-not (Get-Module -ListAvailable -Name Microsoft.Windows.Settings)) { Install-Module
      -Name Microsoft.Windows.Settings -Confirm:$False -Force -AllowPrerelease -AllowClobber
      }"
    executable: "pwsh"

- name: Microsoft.Windows.Settings/WindowsSettings_9ev74ak3
  type: Microsoft.Windows.Settings/WindowsSettings
  metadata:
    description: "Configure Microsoft.Windows.Settings/WindowsSettings"
    winget:
      securityContext: "elevated"
  dependsOn:
  - Microsoft.DSC.Transitional/RunCommandOnSet_f14a1y0q
  properties:
    SystemColorMode: "Dark"
    DeveloperMode: true
    TaskbarAlignment: "Middle"
    AppColorMode: "Dark"

- name: winget_Kitware.CMake
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Kitware.CMake"
  properties:
    id: "Kitware.CMake"
    source: "winget"

- name: winget_Microsoft.PowerShell
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.PowerShell"
  properties:
    id: "Microsoft.PowerShell"
    source: "winget"

- name: winget_LLVM.LLVM
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install LLVM.LLVM"
  properties:
    id: "LLVM.LLVM"
    source: "winget"

- name: winget_Audacity.Audacity
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Audacity.Audacity"
  properties:
    id: "Audacity.Audacity"
    source: "winget"

- name: winget_Docker.DockerDesktop
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Docker.DockerDesktop"
  properties:
    id: "Docker.DockerDesktop"
    source: "winget"

- name: winget_Git.Git
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Git.Git"
  properties:
    id: "Git.Git"
    source: "winget"

- name: winget_OpenSCAD.OpenSCAD
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install OpenSCAD.OpenSCAD"
  properties:
    id: "OpenSCAD.OpenSCAD"
    source: "winget"

- name: winget_SoftwareFreedomConservancy.QEMU
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install SoftwareFreedomConservancy.QEMU"
  properties:
    id: "SoftwareFreedomConservancy.QEMU"
    source: "winget"

- name: winget_VideoLAN.VLC
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install VideoLAN.VLC"
  properties:
    id: "VideoLAN.VLC"
    source: "winget"

- name: winget_Neovim.Neovim
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Neovim.Neovim"
  properties:
    id: "Neovim.Neovim"
    source: "winget"

- name: winget_GNU.Emacs
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install GNU.Emacs"
  properties:
    id: "GNU.Emacs"
    source: "winget"

- name: winget_GitHub.cli
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install GitHub.cli"
  properties:
    id: "GitHub.cli"
    source: "winget"

- name: winget_LGUG2Z.komorebi
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install LGUG2Z.komorebi"
  properties:
    id: "LGUG2Z.komorebi"
    source: "winget"

- name: winget_LGUG2Z.whkd
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install LGUG2Z.whkd"
  properties:
    id: "LGUG2Z.whkd"
    source: "winget"

- name: winget_QMK.QMKToolbox
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install QMK.QMKToolbox"
  properties:
    id: "QMK.QMKToolbox"
    source: "winget"

- name: winget_Vial.Vial
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Vial.Vial"
  properties:
    id: "Vial.Vial"
    source: "winget"


- name: winget_Starship.Starship
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Starship.Starship"
  properties:
    id: "Starship.Starship"
    source: "winget"

# - name: winget_Microsoft.Edge
#   type: Microsoft.WinGet/Package
#   metadata:
#     description: "Install Microsoft.Edge"
#   properties:
#     id: "Microsoft.Edge"
#     source: "winget"

- name: winget_OBSProject.OBSStudio
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install OBSProject.OBSStudio"
  properties:
    id: "OBSProject.OBSStudio"
    source: "winget"

- name: winget_Valve.Steam
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Valve.Steam"
  properties:
    id: "Valve.Steam"
    source: "winget"

- name: winget_GnuWin32.Tar
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install GnuWin32.Tar"
  properties:
    id: "GnuWin32.Tar"
    source: "winget"

- name: winget_DEVCOM.JetBrainsMonoNerdFont
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install DEVCOM.JetBrainsMonoNerdFont"
  properties:
    id: "DEVCOM.JetBrainsMonoNerdFont"
    source: "winget"

- name: winget_Tailscale.Tailscale
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Tailscale.Tailscale"
  properties:
    id: "Tailscale.Tailscale"
    source: "winget"

- name: winget_Microsoft.VCRedist.2015+.x64
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.VCRedist.2015+.x64"
  properties:
    id: "Microsoft.VCRedist.2015+.x64"
    source: "winget"

- name: winget_BurntSushi.ripgrep.GNU
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install BurntSushi.ripgrep.GNU"
  properties:
    id: "BurntSushi.ripgrep.GNU"
    source: "winget"

- name: winget_Discord.Discord
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Discord.Discord"
  properties:
    id: "Discord.Discord"
    source: "winget"

- name: winget_Figma.Figma
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Figma.Figma"
  properties:
    id: "Figma.Figma"
    source: "winget"

- name: winget_GIMP.GIMP.3
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install GIMP.GIMP.3"
  properties:
    id: "GIMP.GIMP.3"
    source: "winget"

- name: winget_JesseDuffield.Lazydocker
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install JesseDuffield.Lazydocker"
  properties:
    id: "JesseDuffield.Lazydocker"
    source: "winget"

- name: winget_JesseDuffield.lazygit
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install JesseDuffield.lazygit"
  properties:
    id: "JesseDuffield.lazygit"
    source: "winget"

- name: winget_Microsoft.OneDrive
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.OneDrive"
  properties:
    id: "Microsoft.OneDrive"
    source: "winget"

- name: winget_alexpasmantier.television
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install alexpasmantier.television"
  properties:
    id: "alexpasmantier.television"
    source: "winget"

- name: winget_cURL.cURL
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install cURL.cURL"
  properties:
    id: "cURL.cURL"
    source: "winget"

- name: winget_eza-community.eza
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install eza-community.eza"
  properties:
    id: "eza-community.eza"
    source: "winget"

- name: winget_AuthorMore.PenpotDesktop
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install AuthorMore.PenpotDesktop"
  properties:
    id: "AuthorMore.PenpotDesktop"
    source: "winget"

- name: winget_junegunn.fzf
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install junegunn.fzf"
  properties:
    id: "junegunn.fzf"
    source: "winget"

- name: winget_sharkdp.fd
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install sharkdp.fd"
  properties:
    id: "sharkdp.fd"
    source: "winget"

- name: winget_sxyazi.yazi
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install sxyazi.yazi"
  properties:
    id: "sxyazi.yazi"
    source: "winget"

- name: winget_tsl0922.ttyd
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install tsl0922.ttyd"
  properties:
    id: "tsl0922.ttyd"
    source: "winget"

- name: winget_zig.zig
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install zig.zig"
  properties:
    id: "zig.zig"
    source: "winget"

- name: winget_Microsoft.VisualStudioCode
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.VisualStudioCode"
  properties:
    id: "Microsoft.VisualStudioCode"
    source: "winget"

- name: winget_Microsoft.AppInstaller
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.AppInstaller"
  properties:
    id: "Microsoft.AppInstaller"
    source: "winget"

- name: winget_Microsoft.UI.Xaml.2.8
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.UI.Xaml.2.8"
  properties:
    id: "Microsoft.UI.Xaml.2.8"
    source: "winget"
- name: winget_Microsoft.VCLibs.Desktop.14
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.VCLibs.Desktop.14"
  properties:
    id: "Microsoft.VCLibs.Desktop.14"
    source: "winget"

- name: winget_Microsoft.WindowsTerminal
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install Microsoft.WindowsTerminal"
  properties:
    id: "Microsoft.WindowsTerminal"
    source: "winget"

- name: msstore_XP99GVQDX7JPR4
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install XP99GVQDX7JPR4"
  properties:
    id: "XP99GVQDX7JPR4"
    source: "msstore"

- name: msstore_XP89DCGQ3K6VLD
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install XP89DCGQ3K6VLD"
  properties:
    id: "XP89DCGQ3K6VLD"
    source: "msstore"

- name: msstore_9N1M7Q4F1KQF
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install 9N1M7Q4F1KQF"
  properties:
    id: "9N1M7Q4F1KQF"
    source: "msstore"

- name: msstore_9PDXGNCFSCZV
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install 9PDXGNCFSCZV"
  properties:
    id: "9PDXGNCFSCZV"
    source: "msstore"

- name: msstore_9NVTPZWRC6KQ
  type: Microsoft.WinGet/Package
  metadata:
    description: "Install 9NVTPZWRC6KQ"
  properties:
    id: "9NVTPZWRC6KQ"
    source: "msstore"
